config/routes.rb
Mpub::Application.routes.draw do

  get "home/index"

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get    '/login'  => 'devise/sessions#new'
    post   '/login'  => "devise/sessions#create"
    delete '/logout' => 'devise/sessions#destroy'
  end
  resources :users do
    get "info", :on => :member
    get "updated", :on => :member
  end

  namespace :api do
    #devise_for :users, :skip => [:sessions, :registrations, :confirmations, :passwords, :unlocks]
    devise_scope :user do
      post "/login" => "sessions#create", :as => :user_session
      delete "/logout" => "sessions#destroy", :as => :destroy_user_session
      get "/status" => "sessions#status"
    end

    resources :categories, :only => [:index, :show]
    match "structure" => 'categories#structure', :via => :get
    match "categories/uploads/:id/:type/:basename.:extension" => 'categories#download', :via => :get, :type => /orig|thumb/

    resources :sub_categories, :only => [:index, :show]
    match "sub_categories/uploads/:id/:type/:basename.:extension" => 'sub_categories#download', :via => :get, :type => /orig|thumb/

    resources :contents, :only => [:index, :show]
    match "contents/uploads/:id/:basename.:extension" => 'contents#download', :via => :get

    match "company" => 'companies#info', :via => :get
    match "companies/uploads/:id/:type/:basename.:extension" => 'companies#download', :via => :get, :type => /orig|thumb/

    match "user_info" => 'users#info', :via => :get
    match "user_profiles/uploads/:id/:type/:basename.:extension" => 'user_profiles#download', :via => :get, :type => /orig|thumb/
    match "customizations/uploads/:id/:type/:basename.:extension" => 'customizations#download', :via => :get, :type => /orig/

    resources :contacts, :only => [:create]

    match "updated" => 'users#updated', :via => :get
  end

  match "profile/:id" => "user_profiles#show", :via => :get, :as => :profile
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'user_profiles#download', :via => :get, :type => /orig|thumb/

  resources :companies
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'companies#download', :via => :get, :type => /orig|thumb/

  resources :customizations, :only => [:edit, :update, :show]
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'customizations#download', :via => :get, :type => /orig|thumb/

  resources :categories do
    resources :contents do
      put 'activate', :on => :member
      put 'unlink', :on => :member
    end
    put 'activate', :on => :member
  end
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'categories#download', :via => :get, :type => /orig|thumb|small/

  resources :sub_categories do
    resources :contents do
      put 'activate', :on => :member
      put 'unlink', :on => :member
    end
    put 'activate', :on => :member
  end
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'sub_categories#download', :via => :get, :type => /orig|thumb/

  resources :contents do
    put 'activate', :on => :member
    put 'unlink', :on => :member
  end
  match "/:controller/uploads/:id/:basename.:extension" => 'contents#download', :via => :get

  mount Ckeditor::Engine => '/ckeditor'
  match "uploads/ckeditor/pictures/:id/:basename.:extension" => 'ckeditor/pictures#download', :via => :get
  match "uploads/ckeditor/attachments/:id/:basename.:extension" => 'ckeditor/attachment_files#download', :via => :get

  resources :contacts, :except => [:edit, :update]
  match "contact_us" => 'contacts#new', :via => :get

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  authenticated :user do
    root :to => 'companies#index', :constraints => RoleConstraint.new(:admin)
    root :to => 'categories#index'
  end

  root :to => redirect("/login")
  #root :to => "home#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :registerable
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :token_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable, :lockable, :timeoutable

  belongs_to :company

  # Relations between users parameters
  has_one :user_profile, :dependent => :destroy
  accepts_nested_attributes_for :user_profile
  has_one :customization, :dependent => :destroy

  # Relations between content
  has_many :categories, :dependent => :destroy
  has_many :sub_categories, :dependent => :destroy
  has_many :contents, :dependent => :destroy

  # Create some attributes before create user
  before_create :create_login, :set_api_updated_at, :generate_user_token
  after_destroy :ensure_an_admin_remains
  before_save :create_customization, :reset_authentication_token, :ensure_user_token


  # Setup accessible (or protected) attributes for your model
  attr_accessible :company_id, :name, :email, :password, :password_confirmation,
                  :remember_me, :role_ids, :user_profile_attributes, :device_udid

  validates :name, :email, presence: true
  validates :name, :email, :uniqueness => { case_sensitive: false }
  validates :device_udid, :uniqueness => { case_sensitive: false }, length: { is: 40 }, allow_blank: true

  def create_login
    email = self.email.split(/@/)
    login_taken = User.where( :login => email[0]).first
    unless login_taken
      self.login = email[0]
    else
      self.login = self.email
    end
  end

  def set_api_updated_at
    self.api_updated_at = Time.now
  end

  def self.find_for_database_authentication(conditions)
    self.where(:login => conditions[:email]).first || self.where(:email => conditions[:email]).first
  end

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  # Fetch current user in models
  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

  private

  def ensure_an_admin_remains
    if User.with_role(:admin).count.zero?
      raise "Can't delete last admin user"
    end
  end

  def create_customization
    self.customization ||= Customization.new({ :user_id => self.id })
  end

  def generate_user_token
    #SecureRandom.base64(15).tr('+/=lIO0', 'pqrsxyz')
    loop do
      token = Devise.friendly_token
      self.user_token = token
      break token unless User.where(:user_token => token).first
    end
  end

  def ensure_user_token
    generate_user_token if self.user_token.blank?
  end

end

app/controllers/api/contents_controller.rb
class Api::ContentsController < Api::BaseController
  before_filter { |c| c.send(:authenticate_by_user_token, params[:user_token]) }
  skip_before_filter :authenticate_user!, :only => [:index, :show, :download]

  rescue_from ActiveRecord::RecordNotFound do
    render :json=> { :success => false, :message => "Invalid content!" }
  end

  # GET /contents
  # GET /contents.json
  def index
    if @read_user
      if params[:device_udid] && @read_user.device_udid && params[:device_udid] == @read_user.device_udid
        @contents = Content.where(user_id: @read_user.id).order("file ASC")
      else
        @contents = Content.where(user_id: @read_user.id, active: true).order("file ASC")
      end

      #render 'contents/index'
    else
      render :json=> { :success => false, :message => "Invalid user!" }
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    if @read_user
      @content = Content.find(params[:id])

      #render 'contents/show'
    else
      render :json=> { :success => false, :message => "Invalid user!" }
    end
  end

  def download
    if @read_user
      @content = Content.find(params[:id])

      path = "#{Rails.root}#{@content.file.url}"
      send_file path, :x_sendfile=>true
    else
      render :json=> { :success => false, :message => "Invalid user!" }
    end
  end

private

  def authenticate_by_user_token(user_token)
    if user_token
      @read_user = User.find_by_user_token(user_token)
    end
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_current_user
  before_filter :load_contentable, :except => [:destroy, :download]

  helper_method :contentable_url, :sort_column, :sort_direction

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to contents_url, :alert => 'Invalid content!'
  end

  add_breadcrumb 'Create a new Content', '', :only => [:new, :create]
  add_breadcrumb 'Edit a Content', '', :only => [:edit, :update]

  # GET /contents
  # GET /contents.json
  def index
    authorize! :index, Content, :message => 'You are not authorized to access this page.'

    if @contentable.nil?
      @contents = Content.where(user_id: current_user.id).order(sort_column + ' ' + sort_direction)
    else
      @contents = @contentable.contents.order(sort_column + ' ' + sort_direction)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json # { render json: @contents }
      format.js
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    if @contentable.nil?
      @content = Content.find(params[:id])
    else
      @content = @contentable.contents.find(params[:id])
    end
    authorize! :show, @content, :message => 'You are not authorized to access this page.'

    respond_to do |format|
      format.html # show.html.erb
      format.json # { render json: @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    if @contentable.nil?
      @content = Content.new
    else
      @content = @contentable.contents.new

      @content.category_ids = [@contentable.id.to_s] if @contentable.class.name == 'Category'
      @content.sub_category_ids = [@contentable.id.to_s] if @contentable.class.name == 'SubCategory'
    end

    #current_ability.attributes_for(:new, Content).each do |key, value|
    #  @content.send("#{key}=", value)
    #end
    #@content.attributes = params[:content]
    authorize! :new, @content, :message => 'You are not authorized to access this page.'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/1/edit
  def edit
    if @contentable.nil?
      @content = Content.find(params[:id])
    else
      @content = @contentable.contents.find(params[:id])
    end
    authorize! :edit, @content, :message => 'You are not authorized to access this page.'
  end

  # POST /contents
  # POST /contents.json
  def create
    if @contentable.nil?
      @content = Content.new(params[:content])
    else
      @content = @contentable.contents.new(params[:content])
    end

    #current_ability.attributes_for(:create, Content).each do |key, value|
    #  @content.send("#{key}=", value)
    #end
    #@content.attributes = params[:content]
    authorize! :create, @content, :message => 'You are not authorized to create new record.'

    @content.user_id = current_user.id

    respond_to do |format|
      if @content.save
        format.html { redirect_to contentable_url, notice: 'Content was successfully created.' }
        format.json { render json: @content, status: :created, location: @content }
      else
        format.html { render action: "new" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    if @contentable.nil?
      @content = Content.find(params[:id])
    else
      @content = @contentable.contents.find(params[:id])
    end
    authorize! :update, @content, :message => 'You are not authorized to update this record.'

    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to contentable_url, notice: 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])
    authorize! :destroy, @content, :message => 'You are not authorized to delete this record.'
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contentable_url }
      format.json { head :no_content }
    end
  end

  def unlink
    if @contentable.nil?
      @content = Content.find(params[:id])
    else
      @content = @contentable.contents.find(params[:id])
    end
    authorize! :unlink, @content, :message => 'You are not authorized to update this record.'

    respond_to do |format|
      if (@content.category_ids.length + @content.sub_category_ids.length) > 1 && !@contentable.nil? && @contentable.contents.delete(@content)
        format.html { redirect_to contentable_url, notice: 'Content link was successfully unlinked.' }
        format.json { head :no_content }
      else
        format.html { redirect_to contentable_url, alert: "Can't unlink content." }
        format.json { head :no_content }
      end
    end
  end

  def download
    @content = Content.find(params[:id])
    authorize! :download, @content, :message => 'You are not authorized to download this record.'

    path = "#{Rails.root}#{@content.file.url}"
    send_file path, :x_sendfile=>true
  end

  def activate
    if @contentable.nil?
      @content = Content.find(params[:id])
    else
      @content = @contentable.contents.find(params[:id])
    end
    authorize! :activate, @content, :message => 'You are not authorized to activate this record.'

    respond_to do |format|
      if @content.update_attribute(:active, !@content.active)
        if current_user.has_role? :admin
          format.html { redirect_to user_url(:id => User.current.id), notice: 'Content was successfully activated/diactivated.' }
        else
          format.html { redirect_to contentable_url, notice: 'Content was successfully activated/diactivated.' }
          format.js
        end
        format.json { head :no_content }
      else
        if current_user.has_role? :admin
          format.html { redirect_to user_url(:id => User.current.id), :alert => "Can't activate/diactivate content!" }
        else
          format.html { redirect_to contentable_url, :alert => "Can't activate/diactivate content!" }
          format.js
        end
        format.json { head :no_content }
      end
    end
  end

private

  def load_contentable
    klass = [Category, SubCategory].detect { |c| params["#{c.name.underscore}_id"] }
    if !klass.nil?
      @contentable = klass.where(user_id: current_user.id, id: params["#{klass.name.underscore}_id"]).first
      if klass.name == 'Category'
        add_breadcrumb "#{@contentable.name}", :sub_categories_path, :unless => :is_admin?
      elsif klass.name == 'SubCategory'
        add_breadcrumb "#{@contentable.category.name}", :sub_categories_path, :unless => :is_admin?
        add_breadcrumb "#{@contentable.name}", :sub_category_contents_path, :unless => :is_admin?
      end
    elsif !get_sub_category.blank?
      @contentable = SubCategory.where(user_id: current_user.id, id: get_sub_category).first
      add_breadcrumb "#{@contentable.category.name}", :sub_categories_path, :unless => :is_admin?
      add_breadcrumb "#{@contentable.name}", :contents_path, :unless => :is_admin?
    else
      add_breadcrumb "SubCategories", :sub_categories_path, :unless => :is_admin?
      add_breadcrumb "Contents", :contents_path, :unless => :is_admin?
    end
  end

  def contentable_url
    klass = [Category, SubCategory].detect { |c| params["#{c.name.underscore}_id"] }
    if !klass.nil?
      if klass.name == 'Category'
        sub_categories_path
      elsif klass.name == 'SubCategory'
        sub_category_contents_path
      end
    else
      contents_path
    end
  end

  def get_sub_category
    if params[:sub_category_id]
      session[:sub_category] = params[:sub_category_id]
    else
      session[:sub_category]
    end
  end

  def sort_column
    Content.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= javascript 'contents_editor' %>

<%= form_for([@contentable, @content], :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.error_messages %>

  <fieldset>
    <legend><%= controller.action_name.capitalize %> content</legend>

    <div class="control-group">
      <%= f.label :category_ids, "Category", :class => 'control-label' %><br />
      <div class="controls">
        <%= f.collection_select :category_ids, Category.order(:name), :id, :name, {}, { :multiple => true } %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :sub_category_ids, "Sub Category", :class => 'control-label' %><br />
      <div class="controls">
        <%= f.select :sub_category_ids, grouped_options_for_select(SubCategory.for_select(User.current.id), f.object.sub_category_ids), {}, { :multiple => true } %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %><br />
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="tabbable tabs-right"> <!-- Only required for left/right tabs -->
      <ul class="nav nav-tabs">
        <li class="<%= "active" if !f.object.ck_name %>"><a href="#tab1" data-toggle="tab">Upload file</a></li>
        <li class="<%= "active" if f.object.ck_name %>"><a href="#tab2" data-toggle="tab">Create text file</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane <%= "active" if !f.object.ck_name %>" id="tab1">
          <div class="control-group">
            <%= f.label :file, :class => 'control-label' %><br />
            <div class="controls">
              <%= f.file_field :file, :class => 'text_field' %><br />

              <% if f.object.file? %>
                <%= File.basename(f.object.file.url) %>
              <% end %>
              <%= f.hidden_field :file_cache %>
            </div>
          </div>
        </div>
        <div class="tab-pane <%= "active" if f.object.ck_name %>" id="tab2">
          <div class="control-group">
            <%= f.label :ck_name, "File name", :class => 'control-label' %><br />
            <div class="controls">
              <%= f.text_field :ck_name, :class => 'text_field' %>
              <%= f.select(:ck_extension, options_for_select(Array[*Content::EXTENSIONS.collect {|v,i| [v, Content::EXTENSIONS.index(v)] }], :selected => f.object.ck_extension)) %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :ck_content, "Conent", :class => 'control-label' %><br />
            <div class="controls">
              <%= f.cktext_area :ck_content, :class => "someclass", toolbar: "MpubToolbar" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="action-group">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <% if current_user.has_role? :admin %>
        <%= link_to 'Cancel', user_url(:id => User.current.id), :class => 'btn' %>
      <% else %>
        <%= link_to 'Cancel', contentable_url, :class => 'btn' %>
      <% end %>
    </div>
  </fieldset>
<% end %>

app/views/contents/_list.html.erb
<table class="table table-hover sortable">
  <tr>
    <th></th>
    <th><%= sortable "name", "File", "contents" %></th>
    <th><%= sortable "extension", "Extension", "contents" %></th>
    <th><%= sortable "file_size", "File size", "contents" %></th>
    <th><%= sortable "content_type", "Content type", "contents" %></th>
    <th></th>
  </tr>

<% @contents.each do |content| %>
  <tr class="content_<%= content.id %> <%= "deactivated" if !content.active %>">
    <td><%= link_to(iconize_is_active(content.active), polymorphic_path([:activate, @contentable, content]), method: :put, remote: true, class: 'activate_link') if can? :activate, Content %></td>
    <td><%= link_to content.name, mpub_file_url(id: content.id, uploader: content.file, cname: c_name(content)) %></td>
    <td><%= content.extension %></td>
    <td><%= content.file_size %></td>
    <td><%= content.content_type %></td>
    <td>
      <div class="btn-group">
        <%= link_to(iconize_show_text, [@contentable, content], class: 'btn btn-mini') if can? :show, Content %>
        <%= link_to(iconize_edit_text, [:edit, @contentable, content], class: 'btn btn-mini') if can? :edit, Content %>
        <%= link_to(iconize_unlink_text, [:unlink, @contentable, content], method: :put, class: 'btn btn-mini btn-warning') if !@contentable.nil? && can?(:unlink, Content) %>
        <%= link_to(iconize_destroy_text, content, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger') if can? :destroy, Content %>
      </div>
    </td>
  </tr>
<% end %>
</table>

app/views/contents/_list_admin.html.erb
<table class="table table-hover sortable">
  <tr>
    <th></th>
    <th>File</th>
    <th>Extension</th>
    <th>File size</th>
    <th>Content type</th>
    <th></th>
  </tr>

<% @contents.each do |content| %>
  <tr>
    <td><%= link_to(iconize_is_active(content.active), activate_content_path(content), method: :put) if can? :activate, Content %></td>
    <td><%= content.name %></td>
    <td><%= link_to File.basename(content.file.url), mpub_file_url(id: content.id, uploader: content.file, cname: c_name(content)) %></td>
    <td><%= content.extension %></td>
    <td><%= content.file_size %></td>
    <td><%= content.content_type %></td>
    <td>
      <div class="btn-group">
        <%= link_to(iconize_edit_text, edit_content_path(content), :class => 'btn btn-mini') if can? :edit, Content %>
        <%= link_to(iconize_destroy_text, content, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger') if can? :destroy, Content %>
      </div>
    </td>
  </tr>
<% end %>
</table>

app/views/contents/activate.js.erb
$('.content_<%= @content.id %> a.activate_link').html("<%= j iconize_is_active(@content.active) %>");

$('tr.content_<%= @content.id %>').toggleClass("deactivated", <%= !@content.active %>);

app/views/contents/edit.html.erb
<%= render 'form' %>

app/views/contents/index.html.erb
<% title "Content List" %>

<% if can? :create, Content %>
  <% new_item "Add Content", [:new, @contentable, :content] %>
<% end %>

<%= content_tag :div, render('list'), :id => "contents_list" %>

app/views/contents/index.js.erb
$('#contents_list').html('<%=j render('list') %>');

app/views/contents/new.html.erb
<%= render 'form' %>

app/views/contents/show.html.erb
<p>
  <b>Categories:</b>
  <ul>
    <% @content.categories.each do |category| %>
      <li><%= category.name %></li>
    <% end %>
  </ul>
</p>

<p>
  <b>Sub categories:</b>
  <ul>
    <% @content.sub_categories.each do |sub_category| %>
      <li><%= sub_category.name %></li>
    <% end %>
  </ul>
</p>

<p>
  <b>Name:</b>
  <%= @content.name %>
</p>

<p>
  <b>File:</b>
  <%= link_to File.basename(@content.file.url), mpub_file_url(id: @content.id, uploader: @content.file, cname: c_name(@content)) %>
</p>

<p>
  <b>Extension:</b>
  <%= @content.extension %>
</p>

<p>
  <b>File size:</b>
  <%= @content.file_size %>
</p>

<p>
  <b>Content type:</b>
  <%= @content.content_type %>
</p>

<p>
  <b>MD5:</b>
  <%= @content.md5_sum %>
</p>

<p>
  <b>Is Active?</b>
  <%= @content.active %>
</p>

<div class="form-actions">
  <% if can? :edit, Content %>
    <%= link_to 'Edit', [:edit, @contentable, @content], :class => 'btn' %> |
  <% end %>

  <%= link_to 'Back', contentable_url, :class => 'btn' %>
</div>