config/routes.rb
Mpub::Application.routes.draw do

  get "home/index"

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get    '/login'  => 'devise/sessions#new'
    post   '/login'  => "devise/sessions#create"
    delete '/logout' => 'devise/sessions#destroy'
  end
  resources :users do
    get "info", :on => :member
    get "updated", :on => :member
  end

  namespace :api do
    #devise_for :users, :skip => [:sessions, :registrations, :confirmations, :passwords, :unlocks]
    devise_scope :user do
      post "/login" => "sessions#create", :as => :user_session
      delete "/logout" => "sessions#destroy", :as => :destroy_user_session
      get "/status" => "sessions#status"
    end

    resources :categories, :only => [:index, :show]
    match "structure" => 'categories#structure', :via => :get
    match "categories/uploads/:id/:type/:basename.:extension" => 'categories#download', :via => :get, :type => /orig|thumb/

    resources :sub_categories, :only => [:index, :show]
    match "sub_categories/uploads/:id/:type/:basename.:extension" => 'sub_categories#download', :via => :get, :type => /orig|thumb/

    resources :contents, :only => [:index, :show]
    match "contents/uploads/:id/:basename.:extension" => 'contents#download', :via => :get

    match "company" => 'companies#info', :via => :get
    match "companies/uploads/:id/:type/:basename.:extension" => 'companies#download', :via => :get, :type => /orig|thumb/

    match "user_info" => 'users#info', :via => :get
    match "user_profiles/uploads/:id/:type/:basename.:extension" => 'user_profiles#download', :via => :get, :type => /orig|thumb/
    match "customizations/uploads/:id/:type/:basename.:extension" => 'customizations#download', :via => :get, :type => /orig/

    resources :contacts, :only => [:create]

    match "updated" => 'users#updated', :via => :get
  end

  match "profile/:id" => "user_profiles#show", :via => :get, :as => :profile
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'user_profiles#download', :via => :get, :type => /orig|thumb/

  resources :companies
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'companies#download', :via => :get, :type => /orig|thumb/

  resources :customizations, :only => [:edit, :update, :show]
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'customizations#download', :via => :get, :type => /orig|thumb/

  resources :categories do
    resources :contents do
      put 'activate', :on => :member
      put 'unlink', :on => :member
    end
    put 'activate', :on => :member
  end
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'categories#download', :via => :get, :type => /orig|thumb|small/

  resources :sub_categories do
    resources :contents do
      put 'activate', :on => :member
      put 'unlink', :on => :member
    end
    put 'activate', :on => :member
  end
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'sub_categories#download', :via => :get, :type => /orig|thumb/

  resources :contents do
    put 'activate', :on => :member
    put 'unlink', :on => :member
  end
  match "/:controller/uploads/:id/:basename.:extension" => 'contents#download', :via => :get

  mount Ckeditor::Engine => '/ckeditor'
  match "uploads/ckeditor/pictures/:id/:basename.:extension" => 'ckeditor/pictures#download', :via => :get
  match "uploads/ckeditor/attachments/:id/:basename.:extension" => 'ckeditor/attachment_files#download', :via => :get

  resources :contacts, :except => [:edit, :update]
  match "contact_us" => 'contacts#new', :via => :get

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  authenticated :user do
    root :to => 'companies#index', :constraints => RoleConstraint.new(:admin)
    root :to => 'categories#index'
  end

  root :to => redirect("/login")
  #root :to => "home#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :registerable
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :token_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable, :lockable, :timeoutable

  belongs_to :company

  # Relations between users parameters
  has_one :user_profile, :dependent => :destroy
  accepts_nested_attributes_for :user_profile
  has_one :customization, :dependent => :destroy

  # Relations between content
  has_many :categories, :dependent => :destroy
  has_many :sub_categories, :dependent => :destroy
  has_many :contents, :dependent => :destroy

  # Create some attributes before create user
  before_create :create_login, :set_api_updated_at, :generate_user_token
  after_destroy :ensure_an_admin_remains
  before_save :create_customization, :reset_authentication_token, :ensure_user_token


  # Setup accessible (or protected) attributes for your model
  attr_accessible :company_id, :name, :email, :password, :password_confirmation,
                  :remember_me, :role_ids, :user_profile_attributes, :device_udid

  validates :name, :email, presence: true
  validates :name, :email, :uniqueness => { case_sensitive: false }
  validates :device_udid, :uniqueness => { case_sensitive: false }, length: { is: 40 }, allow_blank: true

  def create_login
    email = self.email.split(/@/)
    login_taken = User.where( :login => email[0]).first
    unless login_taken
      self.login = email[0]
    else
      self.login = self.email
    end
  end

  def set_api_updated_at
    self.api_updated_at = Time.now
  end

  def self.find_for_database_authentication(conditions)
    self.where(:login => conditions[:email]).first || self.where(:email => conditions[:email]).first
  end

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  # Fetch current user in models
  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

  private

  def ensure_an_admin_remains
    if User.with_role(:admin).count.zero?
      raise "Can't delete last admin user"
    end
  end

  def create_customization
    self.customization ||= Customization.new({ :user_id => self.id })
  end

  def generate_user_token
    #SecureRandom.base64(15).tr('+/=lIO0', 'pqrsxyz')
    loop do
      token = Devise.friendly_token
      self.user_token = token
      break token unless User.where(:user_token => token).first
    end
  end

  def ensure_user_token
    generate_user_token if self.user_token.blank?
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  before_filter { |c| c.send(:authenticate_by_user_token, params[:user_token]) }
  skip_before_filter :authenticate_user!, :only => [:info, :updated]

  rescue_from ActiveRecord::RecordNotFound do
    render :json=> { :success => false, :message => "Invalid user!" }
  end

  def info
    if @read_user
      @user = @read_user

      #render 'users/info'
    else
      render :json=> { :success => false, :message => "Invalid user!" }
    end
  end

  def updated
    if @read_user
      @user = @read_user

      #render 'users/updated'
    else
      render :json=> { :success => false, :message => "Invalid user!" }
    end
  end

private

  def authenticate_by_user_token(user_token)
    if user_token
      @read_user = User.find_by_user_token(user_token)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  #before_filter :set_current_user, only: [:index, :new, :edit, :create, :update, :show]
  before_filter :get_user, only: [:index, :new, :edit]
  before_filter :get_roles, only: [:new, :edit, :create, :update]
  before_filter :get_companies, only: [:index]

  helper_method :sort_column, :sort_direction

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to users_url, :alert => 'Invalid user!'
  end

  #add_breadcrumb "Users", :users_path, :only => [:index, :show, :new, :create]

  def index
    authorize! :index, User, message: 'Not authorized as an administrator.'
    # if current_user.has_role? :admin
    #   @users = User.paginate(page: params[:page], per_page: 30).order(:name)
    # else
    #   @users = User.where(company_id: current_user.company_id).paginate(page: params[:page], per_page: 30).order(:name)
    # end
    @users = User.accessible_by(current_ability).paginate(page: params[:page], per_page: 30).order(sort_column + ' ' + sort_direction)

    respond_to do |format|
      format.html # show.html.erb
      format.json
      format.js
    end
  end

  def show
    @user = User.find(params[:id])
    authorize! :show, @user, message: 'Not authorized as an administrator.'

    # Set User.current to edited user
    session_user_id(params[:id])

    add_breadcrumb "#{@user.name}"

    @categories = Category.where(user_id: params[:id]).order(:name)
    @sub_categories = SubCategory.where(user_id: params[:id]).order(:name)
    set_categories_and_sub_categories_hash(@categories, @sub_categories)
    @contents = Content.where(user_id: params[:id]).order(:file)

    respond_to do |format|
      format.html # show.html.erb
      format.json
      format.js
    end
  end

  def new
    @user = User.new
    current_ability.attributes_for(:new, User).each do |key, value|
      @user.send("#{key}=", value)
    end
    @user.attributes = params[:user]
    authorize! :new, @user, message: 'Not authorized as an administrator.'
  end

  def create
    @user = User.new(params[:user])
    current_ability.attributes_for(:create, User).each do |key, value|
      @user.send("#{key}=", value)
    end
    @user.attributes = params[:user]
    authorize! :create, @user, message: 'Not authorized as an administrator.'

    # Company admin can create users only for his company
    unless current_user.has_role? :admin
      @user.company_id = current_user.company_id
    end

    if @user.save
      redirect_to @user
    else
      render :action => :new, :status => :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user, message: 'Not authorized as an administrator.'

    add_breadcrumb "#{@user.name}"
  end

  def update
    @user = User.find(params[:id])
    authorize! :update, @user, message: 'Not authorized as an administrator.'

    add_breadcrumb "#{@user.name}"

    if params[:user][:password].blank?
      [:password, :password_confirmation].collect{ |p| params[:user].delete(p) }
    end

    # If current user not admin check his current password when hi made some changes
    if !current_user.has_role?(:admin)
      @user.company_id = current_user.company_id
      if !current_user.has_role?(:company_admin)
        @user.errors[:base] << "The password you entered is incorrect" unless @user.valid_password?(params[:user][:current_password])
      end
    end

    # if !current_user.has_role?(:admin)
    #   @user.company_id = current_user.company_id
    #   @user.errors[:base] << "The password you entered is incorrect" unless @user.valid_password?(params[:user][:current_password])
    # end

    # Delete params :current_password to prevent error: Can't mass-assign protected attributes: current_password
    params[:user].delete(:current_password)

    # Check and edit user data
    if @user.errors[:base].empty? and @user.update_attributes(params[:user])
      if current_user.has_role?(:admin) || current_user.has_role?(:company_admin)
        redirect_to @user, notice: "Account has been updated."
      else
        redirect_to root_path
      end
    else
      render action: :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    authorize! :destroy, @user, message: 'Not authorized as an administrator.'

    begin
      @user.destroy
      flash[:notice] = "User #{@user.name} deleted"
    rescue Exception => e
      flash[:error] = e.message
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def info
    @user = User.find(params[:id])
    authorize! :info, @user, message: 'Not authorized as an administrator.'

    respond_to do |format|
      format.json
    end
  end

  def updated
    @user = User.find(params[:id])
    authorize! :updated, @user, message: 'Not authorized as an administrator.'

    respond_to do |format|
      format.json
    end
  end

  # Make the current user object available to views
  #----------------------------------------
  def get_user
    @current_user = current_user
  end

private

  def get_roles
    if current_user.has_role? :admin
      @roles = Role.all
    else
      @roles = Role.find(:all, :conditions => ["name != ?", :admin])
    end
  end

  def get_companies
    @companies = {}

    Company.select('id, name').each do |company|
      @companies[company.id] = company.name
    end
  end

  def set_categories_and_sub_categories_hash(categories, sub_categories)
    @categories_hash = {}
    @sub_categories_hash = {}

    categories.each do |category|
      @categories_hash[category.id] = category.name
    end

    sub_categories.each do |sub_category|
      @sub_categories_hash[sub_category.id] = { category: @categories_hash[sub_category.category_id], name: sub_category.name }
    end
  end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def setup_user(user)
    user.user_profile ||= UserProfile.new
    user
  end
end

app/views/users/_list.html.erb
<table class="table table-hover sortable">
  <thead>
    <tr>
      <th><%= sortable "name", "Name", "users" %></th>
      <th><%= sortable "email", "Email", "users" %></th>
      <%- if can? :show, Role %>
        <th>Role</th>
      <%- end %>
      <%- if can? :show, Company %>
        <th><%= sortable "company_id", "Company", "users" %></th>
      <%- end %>
      <th><%= sortable "created_at", "Signed Up", "users" %></th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <%- if can? :show, Role %>
        <td>
          <ul>
          <%- user.roles.each do |role| %>
            <li><%= role.name.humanize %></li>
          <%- end %>
          </ul>
        </td>
        <%- end %>
        <% if can? :show, Company %>
          <td><%= @companies[user.company_id] %></td>
        <% end %>
        <td><%= user.created_at.to_date %></td>
        <td class="list-actions">
          <%= link_to('✓', edit_user_path(user), :class => 'btn btn-mini') if can? :edit, User %>&nbsp;
          <%= link_to('×', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger') if can? :destroy, User %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @users %>

app/views/users/_profile_info.html.erb
<% present @user.user_profile do |user_profile_presenter| %>
  <div id="profile">
    <%= user_profile_presenter.avatar %>
    <h1><%= user_profile_presenter.linked_name %></h1>
    <dl>
      <dt>Username:</dt>
      <dd><%= user_profile_presenter.full_name %></dd>
      <dt>Member Since:</dt>
      <dd><%= user_profile_presenter.member_since %></dd>
      <dt>Phone:</dt>
      <dd><%= user_profile_presenter.phone %></dd>
      <dt>Fax:</dt>
      <dd><%= user_profile_presenter.fax %></dd>
      <dt>Info:</dt>
      <dd><%= user_profile_presenter.info %></dd>
      <dt>Address:</dt>
      <dd><%= user_profile_presenter.address %></dd>
    </dl>
  </div>
<% end %>

app/views/users/_user_fields.html.erb
<div class="control-group">
  <%= f.label :name, 'Account Name', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :name, :placeholder => 'Account Name' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :email, 'Email', :class => 'control-label' %>
  <div class="controls">
    <%= f.email_field :email, :placeholder => 'Email' %>
  </div>
</div>

<div class="control-group">
<% if can? :show, Role %>
  <label for="role_ids" class="control-label">Role</label>
  <div class="controls">
  <% @roles.each do |role| %>
    <%= hidden_field_tag "user[role_ids][]", nil %>
    <%= radio_button_tag "user[role_ids][]", role.id, @user.role_ids.include?(role.id), id: dom_id(role) %>
    <%= label_tag dom_id(role), role.name.humanize, :class => 'radio inline' %><br />
  <% end %>
  </div>
<% end %>
</div>

<% if can? :manage, Company %>
<div class="control-group">
  <%= f.label :company_id, "Company", :class => 'control-label' %>
  <div class="controls">
    <%= f.collection_select :company_id, Company.order(:name), :id, :name, :prompt => 'Select company' %>
  </div>
</div>
<% end %>

<% if can? :manage_device_udid, User %>
<div class="control-group">
  <%= f.label :device_udid, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :device_udid, :placeholder => 'iPhone/iPad UDID' %>
  </div>
</div>
<% end %>

<%= f.fields_for :user_profile do |ff| %>
  <div class="control-group">
    <%= ff.label :avatar, "Photo", :class => 'control-label' %>
    <div class="controls">
      <% if @user.user_profile.avatar? %>
        <% if @user.user_profile.avatar.url =~ /^\/carrierwave/ %>
          <%= image_tag(@user.user_profile.avatar.thumb.url, :class => 'img-rounded')  %>
        <% else %>
          <%= mpub_image_tag(id: @user.user_profile.id, type: :thumb, uploader: @user.user_profile.avatar, cname: c_name(@user.user_profile)) %>
        <% end %>
        <%= ff.hidden_field :avatar_cache %>
      <% end %>

      <%= ff.file_field :avatar %>
    </div>
  </div>

  <% if @user.user_profile.avatar? %>
    <div class="control-group">
      <%= ff.label :remove_avatar, :class => 'control-label' %>
      <div class="controls">
        <%= ff.check_box :remove_avatar, :class => 'checkbox' %>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= ff.label :full_name, :class => 'control-label' %>
    <div class="controls">
      <%= ff.text_field :full_name, :placeholder => 'Full name' %>
    </div>
  </div>

  <div class="control-group">
    <%= ff.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= ff.text_field :phone, :placeholder => '+xxx (xxx) xxxxxx' %>
    </div>
  </div>

  <div class="control-group">
    <%= ff.label :fax, :class => 'control-label' %>
    <div class="controls">
      <%= ff.text_field :fax, :placeholder => '+xxx (xxx) xxxxxx' %>
    </div>
  </div>

  <div class="control-group">
    <%= ff.label :info, :class => 'control-label' %><br />
    <div class="controls">
      <%= ff.text_area :info, rows: 4, :class => "span4", :placeholder => 'Information' %>
    </div>
  </div>

  <div class="control-group">
    <%= ff.label :address, :class => 'control-label' %><br />
    <div class="controls">
      <%= ff.text_area :address, rows: 4, :class => "span4", :placeholder => 'Address information' %>
    </div>
  </div>
<% end %>

app/views/users/_user_info.html.erb
<table class="table">
  <tbody>
    <tr>
      <td>Name:</td>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <td>Email:</td>
      <td><%= @user.email %></td>
    </tr>
  <% if can? :show, Role %>
    <tr>
      <td>Role:</td>
      <td>
        <ul>
        <%- @user.roles.each do |role| %>
          <li><%= role.name.humanize %></li>
        <%- end %>
        </ul>
      </td>
    </tr>
  <% end %>
  <% if can? :show, Company %>
    <tr>
      <td>Company:</td>
      <td><%= @user.company.name if @user.company %></td>
    </tr>
  <% end %>
    <tr>
      <td>User Token:</td>
      <td><%= @user.user_token %></td>
    </tr>
  <% if can? :manage_device_udid, User  %>
    <tr>
      <td>Device UDID</td>
      <td><%= @user.device_udid %></td>
    </tr>
  <% end %>
  <% if can? :see_timestamps, User %>
    <tr>
      <td>Created at:</td>
      <td><%= @user.created_at %></td>
    </tr>
    <tr>
      <td>Last sign in:</td>
      <td><%= @user.last_sign_in_at %></td>
    </tr>
    <tr>
      <td>Data updated at:</td>
      <td><%= @user.api_updated_at %></td>
    </tr>
    <tr>
      <td>Sign in count:</td>
      <td><%= @user.sign_in_count %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<% title "#{controller.action_name.capitalize} #{@user == @current_user ? 'Your account settings' : "User"}" %>

<%= form_for setup_user(@user), :html => { :multipart => true, :method => :put, :class => 'form-horizontal' }, :validate => true do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> <%= @user == @current_user ? 'Your account settings' : "user #{@user.name}" %></legend>
    <%= f.error_messages %>


    <%= render :partial => 'user_fields', :locals => { :f => f } %>

    <div class="control-group">
      <%= f.label :password, 'Password', :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :autocomplete => "off", :placeholder => '(Leave blank if...)' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password_confirmation, 'Password confirmation', :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :autocomplete => "off", :placeholder => '(Leave blank if...)' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :current_password, 'Current password', :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :current_password, :autocomplete => "off", :placeholder => '(Current password confirm)' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to('Back', users_path, :class => 'btn') if can? :show, User %>
    </div>
  </fieldset>
<% end %>

app/views/users/index.html.erb
<% title "Admin" %>

<% if can? :create, User %>
  <% new_item "New User", new_user_path %>
<% end %>

<%= content_tag :div, render('list'), :id => "users_list" %>

app/views/users/index.js.erb
$('#users_list').html('<%=j render('list') %>');

app/views/users/new.html.erb
<% title "#{controller.action_name.capitalize} user" %>

<%= form_for setup_user(@user), :html => { :multipart => true, :class => 'form-horizontal' }, :validate => true do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> user</legend>
    <%= f.error_messages %>

    <%= render :partial => 'user_fields', :locals => { :f => f } %>

    <div class="control-group">
      <%= f.label :password, 'Password', :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :autocomplete => "off", :placeholder => 'Password' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password_confirmation, 'Password confirmation', :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :autocomplete => "off", :placeholder => 'Password' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit 'Register', :class => 'btn btn-primary' %>
      <%= link_to("Back", users_path, :class => 'btn') if can? :show, User %>
    </div>
  </fieldset>
<% end %>

app/views/users/show.html.erb
<% title 'User' %>

<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">User Info</a></li>
    <li><a href="#tab2" data-toggle="tab">Profile Info</a></li>
    <li><a href="#tab3" data-toggle="tab">Categories</a></li>
    <li><a href="#tab4" data-toggle="tab">SubCategories</a></li>
    <li><a href="#tab5" data-toggle="tab">Contents</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <%= render "user_info" %>
    </div>
    <div class="tab-pane" id="tab2">
      <%= render "profile_info" %>
    </div>
    <div class="tab-pane" id="tab3">
      <%= link_to "New Category", new_category_path, :class => 'btn btn-primary' %>
      <%= content_tag :div, render(partial: "categories/list_admin"), :id => "categories_list" %>
    </div>
    <div class="tab-pane" id="tab4">
      <%= link_to "New Sub Category", new_sub_category_path, :class => 'btn btn-primary' %>
      <%= content_tag :div, render(partial: "sub_categories/list_admin"), :id => "sub_categories_list" %>
    </div>
    <div class="tab-pane" id="tab5">
      <%= link_to "Add Content", new_content_path, :class => 'btn btn-primary' %>
      <%= content_tag :div, render(partial: "contents/list_admin"), :id => "contents_list" %>
    </div>
  </div>
</div>