config/routes.rb
Mpub::Application.routes.draw do

  get "home/index"

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get    '/login'  => 'devise/sessions#new'
    post   '/login'  => "devise/sessions#create"
    delete '/logout' => 'devise/sessions#destroy'
  end
  resources :users do
    get "info", :on => :member
    get "updated", :on => :member
  end

  namespace :api do
    #devise_for :users, :skip => [:sessions, :registrations, :confirmations, :passwords, :unlocks]
    devise_scope :user do
      post "/login" => "sessions#create", :as => :user_session
      delete "/logout" => "sessions#destroy", :as => :destroy_user_session
      get "/status" => "sessions#status"
    end

    resources :categories, :only => [:index, :show]
    match "structure" => 'categories#structure', :via => :get
    match "categories/uploads/:id/:type/:basename.:extension" => 'categories#download', :via => :get, :type => /orig|thumb/

    resources :sub_categories, :only => [:index, :show]
    match "sub_categories/uploads/:id/:type/:basename.:extension" => 'sub_categories#download', :via => :get, :type => /orig|thumb/

    resources :contents, :only => [:index, :show]
    match "contents/uploads/:id/:basename.:extension" => 'contents#download', :via => :get

    match "company" => 'companies#info', :via => :get
    match "companies/uploads/:id/:type/:basename.:extension" => 'companies#download', :via => :get, :type => /orig|thumb/

    match "user_info" => 'users#info', :via => :get
    match "user_profiles/uploads/:id/:type/:basename.:extension" => 'user_profiles#download', :via => :get, :type => /orig|thumb/
    match "customizations/uploads/:id/:type/:basename.:extension" => 'customizations#download', :via => :get, :type => /orig/

    resources :contacts, :only => [:create]

    match "updated" => 'users#updated', :via => :get
  end

  match "profile/:id" => "user_profiles#show", :via => :get, :as => :profile
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'user_profiles#download', :via => :get, :type => /orig|thumb/

  resources :companies
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'companies#download', :via => :get, :type => /orig|thumb/

  resources :customizations, :only => [:edit, :update, :show]
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'customizations#download', :via => :get, :type => /orig|thumb/

  resources :categories do
    resources :contents do
      put 'activate', :on => :member
      put 'unlink', :on => :member
    end
    put 'activate', :on => :member
  end
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'categories#download', :via => :get, :type => /orig|thumb|small/

  resources :sub_categories do
    resources :contents do
      put 'activate', :on => :member
      put 'unlink', :on => :member
    end
    put 'activate', :on => :member
  end
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'sub_categories#download', :via => :get, :type => /orig|thumb/

  resources :contents do
    put 'activate', :on => :member
    put 'unlink', :on => :member
  end
  match "/:controller/uploads/:id/:basename.:extension" => 'contents#download', :via => :get

  mount Ckeditor::Engine => '/ckeditor'
  match "uploads/ckeditor/pictures/:id/:basename.:extension" => 'ckeditor/pictures#download', :via => :get
  match "uploads/ckeditor/attachments/:id/:basename.:extension" => 'ckeditor/attachment_files#download', :via => :get

  resources :contacts, :except => [:edit, :update]
  match "contact_us" => 'contacts#new', :via => :get

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  authenticated :user do
    root :to => 'companies#index', :constraints => RoleConstraint.new(:admin)
    root :to => 'categories#index'
  end

  root :to => redirect("/login")
  #root :to => "home#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/category.rb
# encoding: utf-8

class Category < ActiveRecord::Base
  resourcify

  attr_accessible :active, :name, :user_id, :art, :art_cache, :remove_art, :description

  belongs_to :user, :touch => :api_updated_at

  has_many :sub_categories, :dependent => :destroy, :uniq => true

  has_many :contentions, :as => :contentable, :dependent => :destroy
  has_many :contents, :through => :contentions

  mount_uploader :art, CategoryArtUploader

  validates :name, presence: true,
      uniqueness: { case_sensitive: false, :scope => :user_id },
      length: { maximum: 50 },
      format: { with: /\A[[:word:]\s\-\.\!\?]+\z/i }
  validates :active, :inclusion => { in: [true, false] }
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < Api::BaseController
  # before_filter :authenticate_user!
  before_filter { |c| c.send(:authenticate_by_user_token, params[:user_token]) }
  skip_before_filter :authenticate_user!, :only => [:index, :structure, :show, :download]

  rescue_from ActiveRecord::RecordNotFound do
    render :json=> { :success => false, :message => "Invalid category!" }
  end

  # GET /categories
  # GET /categories.json
  def index
    if @read_user
      if params[:device_udid] && @read_user.device_udid && params[:device_udid] == @read_user.device_udid
        @categories = Category.where(user_id: @read_user.id).order("name ASC")
      else
        @categories = Category.where(user_id: @read_user.id, active: true).order("name ASC")
      end

      #render 'categories/index'
    else
      render :json=> { :success => false, :message => "Invalid user!" }
    end
  end

  # GET /structures
  # GET /structures.json
  def structure
    if @read_user
      if params[:device_udid] && @read_user.device_udid && params[:device_udid] == @read_user.device_udid
        @categories = Category.where(user_id: @read_user.id).order("name ASC")
      else
        @categories = Category.where(user_id: @read_user.id, active: true).order("name ASC")
      end

      render 'api/categories/structure'
    else
      render :json=> { :success => false, :message => "Invalid user!" }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    if @read_user
      @category = Category.find(params[:id])

      #render 'categories/show'
    else
      render :json=> { :success => false, :message => "Invalid user!" }
    end
  end

  def download
    if @read_user
      @category = Category.find(params[:id])

      path = get_path(@category, params[:type])
      send_file path, :x_sendfile=>true
    else
      render :json=> { :success => false, :message => "Invalid user!" }
    end
  end

private

  def get_path(category, type)
    if type
      if type == 'orig'
        "#{Rails.root}#{category.art.url}"
      else
        category.active ? "/#{category.art.url(type.to_sym)}" : "/#{category.art.url(type.to_sym, :sprite)}"
      end
    else
      "/defaults/default_200x200.png"
    end
  end

  def authenticate_by_user_token(user_token)
    if user_token
      @read_user = User.find_by_user_token(user_token)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_current_user

  helper_method :sort_column, :sort_direction

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to categories_url, :alert => 'Invalid category!'
  end

  add_breadcrumb 'Create a new Category', :new_category_path, :only => [:new, :create]
  add_breadcrumb 'Edit a Category', :edit_category_path, :only => [:edit, :update]

  # GET /categories
  # GET /categories.json
  def index
    authorize! :index, Category, message: 'You are not authorized to access this page.'

    @categories = Category.where(user_id: current_user.id).order(sort_column + ' ' + sort_direction)
    set_categories_hash(@categories)

    respond_to do |format|
      format.html # index.html.erb
      format.json # { render json: @categories }
      format.js
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    authorize! :show, @category, message: 'You are not authorized to access this page.'

    respond_to do |format|
      format.html # show.html.erb
      format.json # { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    current_ability.attributes_for(:new, Category).each do |key, value|
      @category.send("#{key}=", value)
    end
    @category.attributes = params[:category]
    authorize! :new, @category, message: 'You are not authorized to access this page.'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    authorize! :edit, @category, message: 'You are not authorized to access this page.'
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    current_ability.attributes_for(:create, Category).each do |key, value|
      @category.send("#{key}=", value)
    end
    @category.attributes = params[:category]
    authorize! :create, @category, message: 'You are not authorized to create new record.'

    @category.user_id = User.current.id #current_user.id

    respond_to do |format|
      if @category.save
        if current_user.has_role? :admin
          format.html { redirect_to user_url(:id => User.current.id), notice: 'Category was successfully created.' }
        else
          format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        end
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])
    authorize! :update, @category, message: 'You are not authorized to update this record.'

    respond_to do |format|
      if @category.update_attributes(params[:category])
        if current_user.has_role? :admin
          format.html { redirect_to user_url(:id => User.current.id), notice: 'Category was successfully updated.' }
        else
          format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    authorize! :destroy, @category, message: 'You are not authorized to delete this record.'
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  def download
    @category = Category.find(params[:id])
    authorize! :download, @category, :message => 'You are not authorized to download this record.'

    path = get_path(@category, params[:type])
    send_file path, :x_sendfile=>true
  end

  def activate
    @category = Category.find(params[:id])
    authorize! :activate, @category, :message => 'You are not authorized to activate this record.'

    respond_to do |format|
      if @category.update_attributes(:active => !@category.active)
        if current_user.has_role? :admin
          format.html { redirect_to user_url(:id => User.current.id), notice: 'Category was successfully activated/diactivated.' }
        else
          format.html { redirect_to categories_url, notice: 'Category was successfully activated/diactivated.' }
          format.js
        end
        format.json { head :no_content }
      else
        if current_user.has_role? :admin
          format.html { redirect_to user_url(:id => User.current.id), alert: "Can't activate/diactivate Category!" }
        else
          format.html { redirect_to categories_url, :alert => "Can't activate/diactivate Category!" }
          format.js
        end
        format.json { head :no_content }
      end
    end
  end

private

  def set_categories_hash(categories)
    @chash = {}
    @categories.each do |cat|
      @chash[cat.id] = cat
    end
  end

  def get_path(category, type)
    if type
      if type == 'orig'
        "#{Rails.root}#{category.art.url}"
      else
        category.active ? "#{Rails.root}#{category.art.url(type.to_sym)}" : "#{Rails.root}#{category.art.url(type.to_sym, :sprite)}"
      end
    else
      "/defaults/default_200x200.png"
    end
  end

  def sort_column
    Category.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper

end

app/views/categories/_form.html.erb
<%= form_for(@category, :html => { :multipart => true, :class => 'form-horizontal' }) do |f| %>
  <%= f.error_messages %>

  <fieldset>
    <legend><%= controller.action_name.capitalize %> category</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %><br />
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :art, "Icon", :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :art %>

        <% if @category.art? %>
          <div>
            <% if @category.id %>
              <%= mpub_image_tag(id: @category.id, type: :thumb, uploader: @category.art, cname: c_name(@category)) %>
            <% else %>
              <%= image_tag(@category.art.thumb.url, :class => 'img-rounded')  %>
            <% end %>
          </div>
          <%= f.hidden_field :art_cache %>
        <% end %>
      </div>
    </div>

    <div class="action-group">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <% if current_user.has_role? :admin %>
        <%= link_to 'Cancel', user_url(:id => User.current.id), :class => 'btn' %>
      <% else %>
        <%= link_to 'Cancel', categories_path, :class => 'btn' %>
      <% end %>
    </div>
  </fieldset>
<% end %>

app/views/categories/_list.html.erb
<%= galery 3, @categories do |id| %>
  <div class="category_<%= @chash[id].id %>">
    <% if @chash[id].active %>
      <%= link_to(mpub_image_tag(id: id, type: :thumb, uploader: @chash[id].art, cname: c_name(@chash[id])), sub_categories_url(:category_id => @chash[id].id), :class => 'lllll') %>
    <% else %>
      <%= link_to(mpub_image_tag(id: id, type: [:thumb, :sprite], uploader: @chash[id].art, cname: c_name(@chash[id])), sub_categories_url(:category_id => @chash[id].id), class: 'lllll') %>
    <% end %>
    <div class="name">
      <b><%= @chash[id].name %></b>&nbsp;&nbsp;&nbsp;
      <%= link_to(iconize_edit, edit_category_path(@chash[id])) if can? :edit, Category %>
      <%= link_to(iconize_is_active(@chash[id].active), activate_category_path(@chash[id]), method: :put, remote: true, class: "activate_link") if can? :activate, Category %>
      <%= link_to(iconize_destroy, @chash[id], method: :delete, data: { confirm: 'Are you sure?' }) if can? :destroy, Category %>
    </div>
  </div>
<% end %>

app/views/categories/_list_admin.html.erb
<table class="table table-hover sortable">
  <tr>
    <th>Icon</th>
    <th>Info</th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <% if category.active %>
      <td><%= mpub_image_tag(id: category.id, type: :small, uploader: category.art, cname: c_name(category)) %></td>
    <% else %>
      <td><%= mpub_image_tag(id: category.id, type: :small, uploader: category.art, cname: c_name(category)) %></td>
    <% end %>
    <td><%= category.name %></td>
    <td>
      <div class="btn-group">
        <%= link_to(iconize_edit_text, edit_category_path(category), :class => 'btn btn-mini') if can? :edit, Category %>
        <%= link_to(
              iconize_is_active_text(category.active),
              activate_category_path(category),
              method: :put,
              :class => 'btn btn-mini btn-info'
            ) if can? :activate, Category %>
        <%= link_to(iconize_destroy_text, category, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger') if can? :destroy, Category %>
      </div>
    </td>
  </tr>
<% end %>
</table>

app/views/categories/activate.js.erb
$('.category_<%= @category.id %> a.activate_link').html("<%= j iconize_is_active(@category.active) %>");
$('.category_<%= @category.id %> a img').attr('src', "<%= mpub_image_url(id: @category.id, type: [:thumb, :sprite], uploader: @category.art, cname: c_name(@category)) %>")

$('div.category_<%= @category.id %>').parent().toggleClass("deactivated", <%= !@category.active %>);

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<% title "Categories" %>

<% if can? :create, Category %>
  <% new_item "New Category", new_category_path %>
<% end %>

<%= content_tag :div, render('list'), :id => "categories_list" %>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Art:</b>
  <br/>
  <%= mpub_image_tag(id: @category.id, type: :orig, uploader: @category.art, cname: c_name(@category)) %>
</p>

<div class="form-actions">
  <% if can? :edit, Category %>
    <%= link_to 'Edit', edit_category_path(@category), :class => 'btn' %> |
  <% end %>
  <%= link_to 'Back', categories_path, :class => 'btn' %>
</div>