config/routes.rb
Mpub::Application.routes.draw do

  get "home/index"

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get    '/login'  => 'devise/sessions#new'
    post   '/login'  => "devise/sessions#create"
    delete '/logout' => 'devise/sessions#destroy'
  end
  resources :users do
    get "info", :on => :member
    get "updated", :on => :member
  end

  namespace :api do
    #devise_for :users, :skip => [:sessions, :registrations, :confirmations, :passwords, :unlocks]
    devise_scope :user do
      post "/login" => "sessions#create", :as => :user_session
      delete "/logout" => "sessions#destroy", :as => :destroy_user_session
      get "/status" => "sessions#status"
    end

    resources :categories, :only => [:index, :show]
    match "structure" => 'categories#structure', :via => :get
    match "categories/uploads/:id/:type/:basename.:extension" => 'categories#download', :via => :get, :type => /orig|thumb/

    resources :sub_categories, :only => [:index, :show]
    match "sub_categories/uploads/:id/:type/:basename.:extension" => 'sub_categories#download', :via => :get, :type => /orig|thumb/

    resources :contents, :only => [:index, :show]
    match "contents/uploads/:id/:basename.:extension" => 'contents#download', :via => :get

    match "company" => 'companies#info', :via => :get
    match "companies/uploads/:id/:type/:basename.:extension" => 'companies#download', :via => :get, :type => /orig|thumb/

    match "user_info" => 'users#info', :via => :get
    match "user_profiles/uploads/:id/:type/:basename.:extension" => 'user_profiles#download', :via => :get, :type => /orig|thumb/
    match "customizations/uploads/:id/:type/:basename.:extension" => 'customizations#download', :via => :get, :type => /orig/

    resources :contacts, :only => [:create]

    match "updated" => 'users#updated', :via => :get
  end

  match "profile/:id" => "user_profiles#show", :via => :get, :as => :profile
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'user_profiles#download', :via => :get, :type => /orig|thumb/

  resources :companies
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'companies#download', :via => :get, :type => /orig|thumb/

  resources :customizations, :only => [:edit, :update, :show]
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'customizations#download', :via => :get, :type => /orig|thumb/

  resources :categories do
    resources :contents do
      put 'activate', :on => :member
      put 'unlink', :on => :member
    end
    put 'activate', :on => :member
  end
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'categories#download', :via => :get, :type => /orig|thumb|small/

  resources :sub_categories do
    resources :contents do
      put 'activate', :on => :member
      put 'unlink', :on => :member
    end
    put 'activate', :on => :member
  end
  match "/:controller/uploads/:id/:type/:basename.:extension" => 'sub_categories#download', :via => :get, :type => /orig|thumb/

  resources :contents do
    put 'activate', :on => :member
    put 'unlink', :on => :member
  end
  match "/:controller/uploads/:id/:basename.:extension" => 'contents#download', :via => :get

  mount Ckeditor::Engine => '/ckeditor'
  match "uploads/ckeditor/pictures/:id/:basename.:extension" => 'ckeditor/pictures#download', :via => :get
  match "uploads/ckeditor/attachments/:id/:basename.:extension" => 'ckeditor/attachment_files#download', :via => :get

  resources :contacts, :except => [:edit, :update]
  match "contact_us" => 'contacts#new', :via => :get

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  authenticated :user do
    root :to => 'companies#index', :constraints => RoleConstraint.new(:admin)
    root :to => 'categories#index'
  end

  root :to => redirect("/login")
  #root :to => "home#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def javascript(*files)
    content_for(:head) { javascript_include_tag(*files) }
  end

  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def new_item(item_title, item_url, options = {}, show_new_item = true)
    content_for(:new_item) { content_tag(:li, link_to(item_title, item_url, options)) }
    @show_new_item = show_new_item
  end

  def show_new_item?
    @show_new_item
  end

  def body_style
    style_attr = ""
    if user_signed_in?
      style_attr << "background-image:url('" + mpub_image_url(id: current_user.customization.id, type: :orig, uploader: current_user.customization.background_image, cname: c_name(current_user.customization)) + "');" if current_user.customization.background_image?
      style_attr << "background-color:" + current_user.customization.background_color + ";" if current_user.customization.background_color
      style_attr << "color:" + current_user.customization.text_color + ";" if current_user.customization.text_color
    end

    style_attr
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>

<%= link_to "MPUB", root_path, :class => 'brand' %>

<div class="nav-collapse">
  <ul class="nav">
    <% if user_signed_in? %>
      <% if can? :manage, Company %>
        <li>
          <%= link_to('Companies', companies_path) %>
        </li>
      <% end %>
      <% if can? :manage, User %>
        <li>
          <%= link_to('Users', users_path) %>
        </li>
      <% end %>
      <% if can? :manage, Contact %>
        <li>
          <%= link_to('Messages', contacts_path) %>
        </li>
      <% end %>
      <% if content_for?(:new_item) %>
        <%= yield(:new_item) %>
      <% end %>
    <% end %>
  </ul>
  <ul class="nav pull-right">
    <li>
      <%= link_to('Contact Us', contact_us_path) %>
    </li>
    <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <i class="icon-user icon-white"></i>
          <b><%= current_user.name %></b>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to('Profile Info', profile_path(current_user.user_profile.id)) %>
          </li>
          <li>
            <%= link_to('Edit account', edit_user_path(current_user.id)) %>
          </li>
          <li>
            <%= link_to('Customization', edit_customization_path(current_user.customization.id)) %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to('Logout', logout_path, :method=>'delete') %>
          </li>
        </ul>
      </li>
    <% else %>
      <li>
        <%= link_to('Login', login_path)  %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MPUB" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag params[:controller] unless params[:controller] =~ /devise/ %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body style="<%= body_style %>">
    <header class="navbar navbar-inverse navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <% if user_signed_in? %>
                <%= render_breadcrumbs :builder => ::BootstrapBreadcrumbsBuilder, :separator => "&raquo;" %>
              <% end %>
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>